
import React from 'react';
import { ImageIcon } from './icons/ImageIcon';

interface ImageDisplayProps {
  generatedImage: string | null;
  isLoading: boolean;
}

const LoadingOverlay: React.FC = () => (
    <div className="absolute inset-0 bg-gray-800/80 backdrop-blur-sm flex flex-col justify-center items-center rounded-xl z-10">
      <div className="w-16 h-16 border-4 border-t-purple-500 border-gray-600 rounded-full animate-spin"></div>
      <p className="mt-4 text-lg text-gray-300">Generating your masterpiece...</p>
    </div>
);

const Placeholder: React.FC = () => (
  <div className="w-full h-full flex flex-col justify-center items-center bg-gray-800/50 border-2 border-dashed border-gray-600 rounded-xl text-gray-500">
    <ImageIcon className="w-24 h-24 mb-4" />
    <p className="text-xl">Your generated image will appear here</p>
  </div>
);

export const ImageDisplay: React.FC<ImageDisplayProps> = ({ generatedImage, isLoading }) => {
  return (
    <div className="relative w-full h-full bg-gray-800 rounded-xl shadow-lg overflow-hidden transition-all duration-300">
      {isLoading && <LoadingOverlay />}
      {!isLoading && !generatedImage && <Placeholder />}
      {generatedImage && (
        <img
          src={generatedImage}
          alt="Generated by AI"
          className="w-full h-full object-cover fade-in"
        />
      )}
    </div>
  );
};
